GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2F0cyIsImlhdCI6MTU3NDYzNTc5OCwiZXhwIjoxNTc0NjM1ODE4fQ.DM1Oqqtci_9m3jLUpyiepcJLWdUvjOuRLZucRbudOF4

###

Post http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2F0cyIsImlhdCI6MTU3NDYzNTc0Nn0.QrAKuARZluOH9-54QxBOtzcli2pLhUbG3WroUmQO2fY"
} 
###
DELETE  http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2F0cyIsImlhdCI6MTU3NDYzNTc0Nn0.QrAKuARZluOH9-54QxBOtzcli2pLhUbG3WroUmQO2fY"
}
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Cats"
}